management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env","bus-refresh", "refresh"]

spring:
  application:
    name: amq-test
  # activemq:

  #   broker-url: tcp://[server]:61616
  #   user: admin
  #   password: admin
  #   use_tls: true
  #   truststore: /certs/truststore.jks
  #   truststorePassword: changeit  
  jms:
    pub-sub-domain: true

amqphub:
  amqp10jms:
    username: admin
    password:  admin 
    remote-url: amqp://127.0.0.1:5672
    pool:
      enabled: true
      maxConnections: 2

server:
  servlet:
    context-path: /amq/api
    port: 8080

#debug: true