management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health", "info", "env","bus-refresh", "refresh"]

spring:
  application:
    name: amq-test
  activemq:
    broker-url: tcp://[server]:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true

server:
  servlet:
    context-path: /amq/api
    port: 8080